
---
apiVersion: v1
kind: Pod
metadata:
  name: probes-demo
  labels:
    app: probes-demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

      # -----------------------
      # Startup Probe
      # -----------------------
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 30
        periodSeconds: 10

      # -----------------------
      # Liveness Probe
      # -----------------------
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3

      # -----------------------
      # Readiness Probe
      # -----------------------
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
        